### ISSUE TITLE
Value cannot be processed as a number

### ISSUE THREAD

**Issue by jamiepryer** [custom-components/sensor.rpi_power#29]
Hey
im getting this error in the logs

arch | armv7l
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
python_version | 3.7.3
timezone | Europe/London
version | 0.94.4
virtualenv | false

> Log Details (WARNING)
> Sun Jun 23 2019 16:13:54 GMT+0100 (British Summer Time)
> Value cannot be processed as a number: <state sensor.rpi_power_status=Everything is working as intended; value=0, friendly_name=RPi Power status, icon=mdi:raspberry-pi @ 2019-06-23T16:13:54.178275+01:00> (Offending entity: Everything is working as intended)

```
  ###installed in HACS####
  #https://github.com/custom-components/sensor.rpi_power
  - platform: rpi_power
    text_state: true

```

```
##https://github.com/custom-components/sensor.rpi_power
- id: 'rpi_power_issue'
  alias: Power Problem Notification
  trigger:
  - platform: numeric_state
    entity_id: sensor.rpi_power_status
    above: 0
    for:
      minutes: 1
  condition:
  action:
    service: persistent_notification.create
    data:
      message: "Charger reported {{ states.sensor.rpi_power_status.state }}"
      title: "Power Supply Issue"
```

**Comment by swetoast** [comment]
Dunno what has recently changed in HA since im running an older version but it seems that HA has an issue with numbers in the automation so my suggestion is checking on what specifically has changed in the automation documentation in HA

**Comment by jamiepryer** [comment]
this now works:

```
- id: rpi_power_issue
  alias: Power Problem Notification
  trigger:
  - platform: numeric_state
    entity_id: sensor.rpi_power_status
    value_template: '{{ state.attributes.value }}'
    above: 0
    for:
      minutes: 1
  condition:
  action:
  - service: persistent_notification.create
    data_template:
      message: "RPI Power reported {{ states.sensor.rpi_power_status.state }}. The state had changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}"
      title: Power Supply Issue
  - service: notify.notify
    data_template:
      message: "RPI Power reported {{ states.sensor.rpi_power_status.state }}. The state had  changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}"
      title: Power Supply Issue
```

**Comment by swetoast** [comment]
Will add as example

**Comment by jamiepryer** [comment]
sorry, this is better, with a 5min limit and updated wording too

```
- id: rpi_power_issue
  alias: Power Problem Notification
  trigger:
  - platform: numeric_state
    entity_id: sensor.rpi_power_status
    value_template: '{{ state.attributes.value }}'
    above: 0
    for:
      minutes: 5
  condition:
  action:
  - service: persistent_notification.create
    data_template:
      message: "RPI Power reported {{ states.sensor.rpi_power_status.state }}. The state had changed from {{ trigger.from_state.state }} "
      title: Power Supply Issue
  - service: notify.notify
    data_template:
      message: "RPI Power reported {{ states.sensor.rpi_power_status.state }}. The state had  changed from {{ trigger.from_state.state }}"
      title: Power Supply Issue
```
